### ISSUE TITLE
Undefined names can raise NameErrors at runtime

### ISSUE THREAD

**Issue by cclauss** [mkocaoglu/CausalGAN#3]
Undefined names can raise [NameError](https://docs.python.org/3/library/exceptions.html#NameError) at runtime.

flake8 testing of https://github.com/mkocaoglu/CausalGAN on Python 2.7.13

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./causal_dcgan/utils.py:147:16: F821 undefined name 'x'
        return x.astype(np.uint8)
               ^
./causal_dcgan/utils.py:149:18: F821 undefined name 'x'
        return ((x+1)/2*255).astype(np.uint8)
                 ^
./figure_scripts/sample.py:157:51: F821 undefined name 'list_labels'
    for name, lab, dfl in zip(model.cc.node_names,list_labels,list_d_fake_labels):
                                                  ^
./figure_scripts/sample.py:157:63: F821 undefined name 'list_d_fake_labels'
    for name, lab, dfl in zip(model.cc.node_names,list_labels,list_d_fake_labels):
                                                              ^
./figure_scripts/sample.py:442:47: F821 undefined name 'nsamples'
            outputs[k]=np.vstack(outputs[k])[:nsamples]
                                              ^
./figure_scripts/sample.py:507:41: F821 undefined name 'nsamples'
                if len(completed_rows)>=nsamples:
                                        ^
./figure_scripts/sample.py:585:40: F821 undefined name 'nsamples'
                outputs[k]=outputs[k][:nsamples]
                                       ^
./figure_scripts/sample.py:592:32: F821 undefined name 'nsamples'
            values=outputs[k][:nsamples]
                               ^
```

**Comment by 22csnyder** [comment]
@cclauss  I'm not familiar with flake8. It seems to check for style consistency. I don't doubt that it would throw an error.

Does this result in a concrete problem I can help with?

**Comment by cclauss** [comment]
> --select=E901,E999,F821,F822,F823

These five errors have _nothing to do with style_.  These are about running the code through the Python abstract syntax tree process looking for syntax errors and other inconsistencies that can halt your program at runtime.

The first error is saying that the `x`is not defined in this context so the code is dangerous.  This can be seen by doing:
* $ cd causal_dcgan/utils.py
* $ python -c "import utils ; utils.make_gif(None, None)"  # [NameError](https://docs.python.org/3/library/exceptions.html#NameError) raised
